name: d_rydes
description: "Driver and Passonger App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #  Utility Package
  http: ^1.2.0
  intl: ^0.19.0
  logger: ^2.0.2
  url_launcher: ^6.2.4
  animated_splash_screen: ^1.3.0

  #  Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  get: ^4.6.5
  get_storage: ^2.1.1
  lottie: ^3.0.0
  passwordfield: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # Local Asset
  assets:
    - assets/
    - assets/logos/
    - assets/icons/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Thin.ttf
          style: normal